// ============================================================================
// BASIS PENGETAHUAN "ASISTEN KD" (widget chat melayang di panel)
//
// ATURAN WAJIB: setiap menambah / mengubah fitur, menu, tab admin, atau
// pengaturan sistem, PERBARUI file ini di commit yang sama. Asisten hanya
// "tahu" apa yang tertulis di sini; test/assistant-kb.spec.ts MENGGAGALKAN CI
// bila ada menu, tab admin, atau pengaturan sistem yang belum dijelaskan.
// Naikkan ASSISTANT_KB_VERSION setiap kali isi berubah.
// Jangan menulis rahasia (password, key, token) di sini.
// ============================================================================

export const ASSISTANT_KB_VERSION = "2026-10-08.35";

/** Penjelasan per menu. Kunci = id navigasi (nav-<kunci>) di ui-src/Index.html. */
export const KB_PAGES: Record<string, { title: string; text: string }> = {
	home: {
		title: "Dashboard",
		text: "Ringkasan hari ini (WIB). Bagian atas: salam sesuai jam + tanggal, chip user & role, chip 'Berikutnya HH:MM · Xj Ym lagi' (hitung mundur ke sesi prediksi berikutnya) dan status 'Panel online' (muncul 'Mode maintenance' bila admin mengaktifkannya). Empat kartu: Berhasil, Gagal, Pengiriman, Aktivitas. 'Aktivitas hari ini per jam': batang aktivitas tiap jam (ADMIN: 'Total semua user'; operator/viewer: 'Akun Anda' saja), bagian merah = gagal, batang bergaris putus = jam sekarang, arahkan kursor untuk melihat angka; donat 'sukses' = persen Berhasil dibanding (Berhasil + Gagal). 'Jadwal prediksi hari ini': semua sesi auto-posting + kata-kata penutup dengan lencana SELESAI / BERIKUTNYA / jumlah pasaran (jamnya diatur admin di Admin > Data Master). 'Aktivitas terbaru': riwayat akun Anda hari ini; tombol 'Lihat semua' membuka menu Aktivitas. 'Akses cepat': ubin menu yang sering dipakai. 'Operator teraktif hari ini' (hanya ADMIN): lima user dengan aktivitas terbanyak. Operator/viewer hanya melihat angka milik akunnya sendiri; ADMIN melihat semua user. Data di-cache singkat (bawaan 25 dtk, diatur di Pengaturan Sistem), jadi bisa tertinggal beberapa detik."
	},
	result: {
		title: "Result",
		text: "Alur harian utama. 1) Salin teks hasil pengeluaran dari Telegram, 2) klik 'Tempel' (atau tempel manual) di kotak 'Teks mentah' — teks otomatis diproses: panel mengenali Pasaran, Prize 1/2/3, Shio, angka 2D, lalu tampil di 'Monitor hasil real-time' dan 'Live preview output'. 3) Pastikan Status 'BENAR', lalu klik 'KIRIM SEMUA SISTEM' (TG = Telegram, LT = LinkTree, PZ = Panel-Z) untuk mengirim ke semua website milik akun Anda. Sistem mencegah pengiriman ganda (duplikat diblokir). Bila salah satu sistem gagal, hasil tiap sistem tampil dan bisa dikirim ulang. 'Kirim manual ke Panel-Z': pilih pasaran + isi angka, klik 'Kirim ke Panel-Z' (tombol 'Tempel Angka' mengambil dari clipboard). 'Salin cepat' menyalin Prize 1/2/3, teks Telegram, Judul LinkTree, Pesan LinkTree, dan teks Panel-Z.",
	},
	prediction: {
		title: "Prediksi",
		text: "Halaman 'Pusat Prediksi Pasaran'. Jadwal prediksi per sesi jam (02:35, 06:15, 08:40, 12:40, 16:00, 21:20, 23:25) dan kata-kata penutup (06:15 & 16:00). Per baris: 'Copy' menyalin teks prediksi unik per website; 'Send Auto' mengirim ke semua website milik akun yang belum terkirim hari ini (tanpa duplikat; kolom Status menampilkan 'x dari y website hari ini'). Kartu 'Kata-kata penutup' punya Copy dan Send Auto sendiri dengan pilihan sesi 06:15/16:00. 'Refresh Status' memuat ulang status kirim. Prediksi juga dikirim OTOMATIS oleh Auto Posting (lihat Admin > Maintenance & Log) selama ada operator login; website yang belum punya token Telegram prediksi tidak bisa dikirimi.",
	},
	invest: {
		title: "AutoCheck Invest",
		text: "Memindai semua pasaran di panel agen dan menandai user yang melebihi batas line (2D/3D/4D) hari ini + kemarin. Isi dulu 'Setting panel agen': Base URL, PHPSESSID (wajib; cookie sesi login agen yang masih hidup), koderedis (bila tetap 'session expired'), Cookie mentah (opsional), Limit 2D/3D/4D, dan Daftar pasaran (isi hanya jika scan menghasilkan 0 data). Klik 'Simpan setting', lalu 'Cek koneksi/session' untuk memastikan cookie valid. 'Mulai scan' memulai; 'Lanjutkan scan' meneruskan bila terhenti; 'Reset' mengulang; 'Refresh hasil' memuat hasil terbaru. Hasil muncul di 'User lewat batas'. Bila 'session expired', login ulang ke panel agen dan ambil PHPSESSID baru. Nilai default limit bisa diubah admin di Admin > Pengaturan Sistem.",
	},
	"auto-input": {
		title: "Auto Prediksi",
		text: "Halaman ini punya 3 tab: 'Sesi Website' (pasang & uji PHPSESSID tiap website; ada panduan 3 langkah yang bisa dibuka), 'Toto Macau' (Auto Check Toto Macau & Toto Macao 5D: status, filter Beres/Menunggu/Bermasalah, LOG KEGIATAN yang bisa dibuka, tabel per draw, tombol 'Cek & isi sekarang') dan 'Riwayat Job' (job Auto Prediksi 7 hari dengan filter Semua/Perlu dicek/Selesai, urutkan, dan kolom cari). Angka kecil di tab = jumlah sesi tersimpan / baris bermasalah / job perlu dicek; baris saklar AKTIF/NONAKTIF ada di atas semua tab. Setelah 'KIRIM SEMUA SISTEM' di menu Result, angka result otomatis diinput ke menu 'Nomor Keluar' di admin website lalu di-'Hitung' sesuai pasaran dan jumlah prize. Cara memakai: pada tiap kartu website (hanya website milik akun), tempel PHPSESSID dari Chrome yang sedang login admin website (F12 > Application > Cookies), klik 'Simpan', lalu 'Uji (tanpa kirim)' untuk memastikan sesi hidup sebelum diaktifkan. Tombol 'Aktifkan' di bagian atas menyalakan fitur (status berubah 'AKTIF'). Bila sesi habis, input gagal dan Anda input manual — tempel PHPSESSID baru. Nilai PHPSESSID tidak pernah ditampilkan ulang. Tiap website hanya boleh memakai server admin yang sudah ditetapkan. Kartu 'Auto Check Toto Macau & Toto Macao 5D' memperlihatkan angka yang dibaca otomatis dari admin (tanggal & jam draw, website, pasaran tujuan, angka, status). Tabel di bawah memuat riwayat job (Waktu, Website, Result, Status, Keterangan) untuk 7 hari terakhir (admin bisa mengubahnya 1-30 hari di Pengaturan Sistem › Auto Prediksi); job tidak dihapus otomatis sebelum itu. Kolom pencarian di atas tabel menyaring riwayat (website, pasaran, angka, status GAGAL/SELESAI, keterangan; beberapa kata = semuanya harus cocok). Job yang GAGAL dicoba ulang OTOMATIS 2 kali dengan jeda 2 menit (mis. gagal 00:23 → coba 00:25 → coba 00:27, tanpa klik user); angka yang sudah masuk tidak pernah dikirim dobel, yang dilanjutkan hanya Hitung. Setelah percobaan habis status tetap GAGAL dan muncul popup merah 'PERINGATAN: Auto Prediksi GAGAL' di tengah layar (di menu mana pun Anda berada, sekali saja) berisi daftar website/pasaran yang perlu dicek manual di admin website; tombol BUKA AUTO PREDIKSI membuka menunya.",
	},
	"lap-admin": {
		title: "Lap Admin",
		text: "Laporan harian dari panel admin website. Pilih tanggal (Tanggal mulai/selesai, atau tombol Hari ini / Kemarin / 7 hari), klik 'TARIK DATA'. Data ditarik oleh scraper di GitHub Actions (butuh Link Admin + Cookie Admin di menu Setting), progres tampil di 'Progres & riwayat tarik data' dan boleh ditinggal ke menu lain. Hasil: 'Laporan Register' (bisa di-Copy); kartu Total Deposit (total History Operator DIKURANGI operator khusus), Total <operator khusus> seperti Blazz/Khanpay, dan Total Withdraw — sesuai tanggal yang ditarik; Total Selisih, ID Selisih (tombol Copy menyalin daftar ID selisih), WD PGA-IDF; lalu tabel Register (filter Non Referral / With Referral), ID Selisih, Report Agent (filter Action & Operator), Withdraw PGA-IDF, dan Riwayat Koin. Tiap tabel punya pencarian dan tombol Copy. Daftar operator khusus diatur admin di Admin > Pengaturan Sistem. Bila cookie kedaluwarsa, tarik data gagal: ambil Cookie Admin baru dan simpan di Setting. Data lama (sebelum fitur total) menampilkan petunjuk 'klik TARIK DATA'.",
	},
	"lap-motion": {
		title: "Lap Motion",
		text: "Laporan Motion (DP PGA, PGA Pending/Error, PGA Withdraw). Data ditarik lewat Console browser (bukan server) karena Motion sering menolak trafik server: buka panduan 'Lihat cara pakai', buka tab Motion yang sudah login, salin 'Skrip Deposit' (menu RIWAYAT PGA) dan/atau 'Skrip Withdraw' (menu WD REQUEST), tekan F12 > Console, tempel, Enter, isi tanggal, tunggu 'terkirim ke panel OK', lalu klik 'Muat Ulang'. Boleh menjalankan salah satu dulu; data yang belum dijalankan tidak tertimpa kosong. Hasil: kartu ringkasan dan tabel Motion DP PGA, PGA Pending/Error, PGA Withdraw dengan pencarian & Copy.",
	},
	"pga-pending": {
		title: "PGA Pending",
		text: "Daftar live withdraw berstatus PGA Pending dari motionv2.com (WD Request). Tidak ditarik server: jalankan skrip dari panduan 'Cara pakai' di Console tab Motion (menu WD REQUEST), biarkan tab Motion TETAP TERBUKA; daftar di panel update sendiri tiap ±2 detik. Baris yang hilang dari WD Request otomatis hilang. Tabel PGA Pending dan WD Listed punya kotak centang untuk menyalin baris terpilih (Copy menyalin yang dicentang; tanpa centang menyalin semua yang tampil). 'Baris aktif' menunjukkan jumlah data masuk.",
	},
	"lap-mozart": {
		title: "Lap Mozart",
		text: "Laporan Deposit & Withdraw Mozart (m-banking). Mozart diproteksi Cloudflare sehingga data diambil lewat Console tab Mozart: 'Salin Skrip', buka tab Mozart yang sudah login, F12 > Console, tempel, Enter, isi tanggal, tunggu 'terkirim ke panel OK', lalu 'Muat Ulang'. Hasil: kartu (DP Done By Bot, Nominal DP Bot, WD Selesai, Nominal WD Selesai) dan tabel Mozart Deposit/Withdraw per rekening bank dengan total.",
	},
	"lap-setting": {
		title: "Setting (Laporan Harian)",
		text: "Kredensial milik akun Anda untuk menu Laporan Harian: Link Admin + Cookie Admin (nilai PHPSESSID=...; dipakai Lap Admin), Link Motion + Token Motion (header x-access-token) + Vendor ID (Lap Motion), dan akun Mozart. Ambil Cookie/Token dari DevTools (F12). Klik simpan; data tersimpan di database panel dan dipakai semua menu Laporan Harian. Cookie dan token bisa kedaluwarsa — bila tarik data gagal 'cookie kedaluwarsa', ambil yang baru.",
	},
	activity: {
		title: "Aktivitas",
		text: "Riwayat aktivitas (7 hari terakhir; lama retensi diatur admin). Operator melihat aktivitas akunnya sendiri hari ini; Admin melihat semua user. Kartu ringkasan: Aktivitas hari ini, Login, Pengiriman, Berhasil, Gagal. Filter: pencarian teks, User (admin), Aksi, Status, rentang tanggal; klik 'Terapkan' atau 'Reset'. Tabel: Waktu, Username, Aksi, Status (Berhasil/Gagal/Sebagian-Diblokir/Info), Detail, Isi/Data (klik untuk memperluas teks panjang). Pagination di atas tabel.",
	},
	"livechat-sessions": {
		title: "Sesi Chat (Live Chat)",
		text: "Auto-reply DayLiveChat. Bot membalas otomatis member yang spam/kasar HANYA di sesi yang Anda aktifkan; sesi lain tetap dibalas manual oleh CS. Daftar sesi (milik Anda saja) muncul otomatis begitu bot 🤖 aktif di halaman DayLiveChat CS (dipasang lewat Console, lihat cara pasang di bawah) dan Anda login CS. Nyalakan switch 'BOT AKTIF' pada sesi member yang ingin dibalas otomatis. 'Sinkron terakhir' menunjukkan kapan userscript terakhir mengirim data. Cara pasang bot (lewat Console browser, tanpa ekstensi dan tanpa unduh file; kode dimuat dari panel jadi selalu terbaru): (1) buka halaman DayLiveChat CS dan login seperti biasa; (2) tekan F12 lalu buka tab Console; (3) pertama kali saja, ketik 'allow pasting' lalu Enter (Chrome meminta izin tempel); (4) di panel klik tombol 'SALIN KODE CONSOLE' (menu Live Chat > Sesi Chat), tempel (Ctrl+V) di Console, tekan Enter — tombol kecil 🤖 muncul di pojok kanan bawah halaman DayLiveChat, F12 boleh ditutup; (5) klik 🤖, tempel Kunci Bot (salin dari kartu 'KUNCI BOT KAMU' di halaman Sesi Chat; alamat panel sudah terisi), simpan, nyalakan — pengaturan diingat browser, cukup sekali; (6) sesi chat muncul di daftar Sesi Chat, nyalakan switch pada sesi yang mau dibalas otomatis. Bot hanya hidup selama tab DayLiveChat CS terbuka: bila halaman di-refresh atau ditutup, ulangi langkah 2-4 (tempel kode Console lagi; Kunci Bot tidak perlu diisi ulang). Kalau muncul popup 'Bot gagal dimuat', situs memblokir skrip dari luar — beri tahu admin. Bookmark/bookmarklet TIDAK bisa dipakai karena halaman DayLiveChat tidak menjalankannya. Kunci Bot bersifat PER PENGGUNA: sesi chat, template balasan, dan riwayat tiap pengguna terpisah (tidak tampil di menu pengguna lain); tombol 'BUAT KUNCI BARU' mematikan kunci lama bila bocor; pengguna baru perlu menambah template sendiri di menu Template Balasan, kalau tidak bot tidak membalas. Bot tidak bisa jalan dari server atau dari halaman panel sendiri: login CS DayLiveChat dikunci ke IP tertentu dan browser melarang panel membaca situs lain. Alternatif: Tampermonkey (userscript) atau Agent Node.js (folder livechat-agent) — jangan dijalankan bersamaan. Hanya ADMIN/OPERATOR.",
	},
	"livechat-templates": {
		title: "Template Balasan (Live Chat)",
		text: "Daftar kalimat balasan yang dipakai bot Live Chat. Template bersifat PER PENGGUNA: setiap pengguna hanya melihat dan memakai template miliknya sendiri (template admin tidak dipakai pengguna lain). Tambah, ubah, aktif/nonaktifkan, atau hapus template; urutan (sort) menentukan prioritas. Bot memilih template aktif saat membalas sesi yang BOT AKTIF.",
	},
	admin: {
		title: "Admin",
		text: "Hanya ADMIN. Tab: Users, Website, Sesi Aktif, Auto Posting, Pengaturan Sistem, Data Master, Integrasi, Maintenance & Log (penjelasan tiap tab ada di bagian Admin).",
	},
	"bot-dashboard": {
		title: "Bot News — Dashboard",
		text: "Khusus role BOT. Dari atas ke bawah: (1) Toggle 'AUTO-POST' menyalakan posting otomatis terjadwal. (2) Peringatan merah bila ada yang perlu dibenahi: Blogger belum terhubung/terputus (tombol Hubungkan Ulang) atau tidak ada AI provider aktif (Kelola). (3) TIGA KARTU JALUR dengan susunan sama — Blogger, Situs Sendiri, Template Facebook: angka besar = jumlah HARI INI, batang = pemakaian batas harian (Blogger = 'Jatah Blogger', Template FB = batas harian FB; Situs Sendiri tanpa batas harian, hanya maks per putaran), 'Total semua' = jumlah sepanjang waktu, lencana = status koneksi (Terhubung/Terputus/Belum terhubung, Aktif, Otomatis/Manual). (4) 'Jalankan sekarang': pilih 'Send ke' (Blogger + Website Sendiri / Blogger saja / Website Sendiri saja) dan Jumlah artikel (kosong = ikut 'Artikel per proses' di Setting dan jalan sampai antrean habis), klik JALANKAN (lewat GitHub Actions; progres tampil di bawahnya), tombol putar = refresh. (5) 'Tren 7 hari terakhir': tiga batang per hari (oranye Blogger, hijau Situs Sendiri, biru Template FB) + total per hari. (6) 'Antrean & kesehatan': Antre artikel, Error, Total tayang (Blogger + Situs), Sumber berita aktif, AI provider aktif, status Auto-post. (7) 'Log artikel terbaru': 40 artikel terakhir dengan lencana status (Blogger/Antre/Error/Dilewati/Situs), tautan sumber & hasil post, pesan error, tombol Lewati untuk yang Antre/Error.",
	},
	"bot-sources": {
		title: "Bot News — Sumber Berita",
		text: "Khusus role BOT. Daftar sumber berita (RSS/Google News) per kategori. Tambah sumber (nama, URL, jenis, kategori), aktif/nonaktifkan, atau hapus. Bot mengambil berita baru dari sumber aktif lalu ditulis ulang oleh AI.",
	},
	"bot-history": {
		title: "Bot News — Riwayat Posting",
		text: "Khusus role BOT. Satu kartu dengan dua tab: 'Blogger' (artikel yang tayang di Blogger, judul membuka hasil posting) dan 'Situs Sendiri' (artikel di situs berita sendiri; judul membuka halaman artikelnya). Dua jalur sengaja dipisah supaya tidak dobel: artikel di Situs Sendiri tidak ikut diposting ke Blogger. Angka di tab = jumlah riwayat; kolom cari menyaring judul. Tiap baris: waktu, judul, sumber/kategori, tautan sumber asli.",
	},
	"bot-fbdirect": {
		title: "Bot News — Template FB",
		text: "Khusus role BOT. Template teks posting Facebook yang dibuat bot; bisa digenerate dan dijalankan langsung.",
	},
	"bot-config": {
		title: "Bot News — Setting",
		text: "Khusus role BOT. Tab: AI Provider (daftar provider: nama, Base URL, API key, model, urutan prioritas, kuota/masa aktif; Tambah Provider; pemakaian terakhir), Konten & Artikel (panjang & gaya), Jadwal Posting, Blogger (hubungkan akun), Sosial & Promo. Simpan lewat tombol SIMPAN SETTING. Asisten KD memakai key khusus sendiri (Admin › Pengaturan Sistem › Asisten KD); AI Provider di sini hanya dipakai asisten bila admin belum mengisi key khusus.",
	},
};

/** Penjelasan tab menu Admin. Kunci = data-admin-tab di ui-src/Index.html. */
export const KB_ADMIN_TABS: Record<string, { title: string; text: string }> = {
	users: {
		title: "Users",
		text: "Kelola akun: Tambah User / edit / hapus / buka kunci. Isi username, nama, password, role (ADMIN, OPERATOR, VIEWER, BOT), status (AKTIF, NONAKTIF, TERKUNCI), website yang boleh dipakai (kode seperti HUGO,FOLA), akses menu (centang menu yang boleh; semua dicentang = semua menu role-nya), serta izin Telegram/LinkTree/Panel-Z. Mengubah password, menonaktifkan, me-rename, atau menghapus akun otomatis mencabut semua sesinya. Tombol kunci = reset login gagal dan buka kunci akun. Kolom 'Menu' menunjukkan jumlah menu yang diizinkan. Tabel bisa dicari/filter role & status dan digulir ke bawah.",
	},
	sites: {
		title: "Website",
		text: "Kelola data tiap website: nama tampilan, token & chat ID Telegram (result) dan Telegram prediksi, email & password LinkTree, serta URL/user/password Panel-Z. Website baru harus punya kode yang dikenali sistem. Data ini dipakai saat 'KIRIM SEMUA SISTEM' dan Auto Posting. Jangan bagikan isi kolom password.",
	},
	sesi: {
		title: "Sesi Aktif",
		text: "Daftar user yang sedang login (jumlah sesi, waktu login, sesi berakhir) dan kolom 'Auto Post' (ikut auto posting prediksi atau tidak). Tombol 'Refresh sesi' memuat ulang.",
	},
	autopost: {
		title: "Auto Posting",
		text: "Mengaktifkan/menonaktifkan auto posting prediksi: selama ada operator login, prediksi tiap sesi jam dan kata-kata penutup dikirim otomatis ke website milik operator itu (Smart Lock mencegah dobel). Digerakkan cron eksternal yang memanggil 'URL CRON' tiap menit. Tombol: URL CRON, Jalankan Sekarang, Aktifkan/Nonaktifkan.",
	},
	integrasi: {
		title: "Integrasi",
		text: "Hanya ADMIN. Koneksi ke layanan luar yang dulu tertanam di kode/variabel Cloudflare/file GitHub, kini diatur dari panel. Tiap kolom punya lencana sumber nilai: 'DIISI ADMIN' (override dari sini), 'DARI CLOUDFLARE' (variabel lama), atau 'BAWAAN' (nilai di kode); kolom dikosongkan atau tombol BAWAAN = kembali ke bawaan. Kelompok: (1) GITHUB ACTIONS — Token GitHub (rahasia: tidak pernah ditampilkan ulang, hanya 4 karakter terakhir; kolom kosong = tidak diubah), Repo scraper Laporan Harian (workflow scrape.yml, tombol Tarik Data), Repo Bot News turbo (news-turbo.yml), Repo Invest turbo (invest-turbo.yml). Token harus fine-grained dengan izin Actions: Read and write dan MENCAKUP semua repo itu (KD-scraper dan KD-Group-Panel). (2) ALAMAT PANEL — alamat publik yang dipanggil balik scraper. (3) LINKTREE — URL login, URL kirim notifikasi, dan API key (rahasia) untuk pengiriman hasil ke LinkTree. (4) WEB BERITA & STRUK — alamat web berita sendiri (backlink, caption Facebook, sitemap) dan alamat dasar struk disbursement WD Listed (harus berakhir '/'). (5) KEAMANAN AUTO INPUT — domain admin yang diizinkan (pagar anti penyalahgunaan; Auto Input hanya boleh ke domain ini dan sub-domainnya). Di bawah ada TES KONEKSI GITHUB: membaca (tanpa menjalankan apa pun) tiga workflow dan memberi diagnosa per repo — 401 token salah/kedaluwarsa, 403 izin kurang, 404 repo/workflow tidak ditemukan atau token tidak mencakup repo itu. Simpan dulu sebelum mengetes. Nilai tidak valid ditolak dengan pesan jelas; berlaku ±15 detik.",
	},
	datamaster: {
		title: "Data Master",
		text: "Hanya ADMIN. Daftar yang dulu tertanam di kode kini bisa diatur tanpa deploy; tiap daftar berupa kartu yang dibuka dengan klik judulnya, dengan tombol SIMPAN dan KEMBALIKAN KE BAWAAN (klik dua kali). Lencana 'BAWAAN' = masih nilai asli, 'DIUBAH ADMIN' = sudah dikustom. Perubahan berlaku ±15 detik; data tidak valid ditolak dengan pesan yang menjelaskan baris mana yang salah, dan data rusak otomatis kembali ke bawaan (sistem tidak bisa lumpuh). Isi: (1) AUTO POSTING — 'Jadwal Prediksi': tiap sesi punya jam (WIB, HH:MM, tidak boleh kembar), nama sesi, dan daftar pasaran (satu per baris, maks 30), 1-12 sesi; urutan sesi = nomor sesi PRED-1, PRED-2… yang dipakai penjaga anti-kirim-ganda, jadi tambah sesi baru di bawah dan jangan menukar urutan di tengah hari. 'Kata-kata Penutup Prediksi': 1-4 jam kiriman penutup (bawaan 06:15 dan 16:00) + 1-20 variasi kalimat. 'Pool Tebak Shio': pilihan teks TEBAK SHIO di prediksi (satu per baris, mis. ANJING - KUDA). (2) SHIO — 'Peta Shio': 12 nama shio untuk sisa bagi 12 dari dua angka terakhir Prize 1 (sisa 1 = nama pertama … sisa 0 = nama ke-12) plus shio khusus angka 00 (bawaan KELINCI); dipakai untuk memeriksa/mengoreksi baris 'Shio :' pada hasil (status BENAR/SALAH) dan pratinjau di browser; nama huruf saja, tidak boleh kembar. (3) PASARAN — 'Peta Pasaran → Panel-Z': nama pasaran di teks hasil → slug Panel-Z, format 'NAMA PASARAN = slug' per baris (salah slug = kirim Panel-Z gagal untuk pasaran itu); 'Daftar Pasaran AutoCheck Invest': daftar bawaan scan Invest, format 'kode = NAMA' (kode panel agen seperti p6680); tiap user tetap bisa menimpa daftarnya sendiri di menu AutoCheck Invest. (4) AUTO INPUT — 'Server Admin per Website': host admin tiap website (host → kode website); host harus di domain yang diizinkan (tab Integrasi). (5) BOT NEWS — 'Kata Anchor Backlink' (3-40 kata huruf saja) dan 'Hashtag Tetap Caption Facebook' (0-15). Angka batas auto-posting (masa kunci sesi, maks percobaan, kunci anti-tumpang-tindih, toleransi susulan) ada di tab Pengaturan Sistem.",
	},
	lapops: {
		title: "Pengaturan Sistem",
		text: "Dua bagian. (1) 'Pengaturan Sistem': nilai angka dengan batas aman yang dipakai server — lama simpan log aktivitas, toleransi susulan auto-post, batas salah password & lama kunci akun, masa berlaku sesi & maks sesi per user, default limit AutoCheck Invest 2D/3D/4D, dan pengaturan Asisten KD (aktif/nonaktif, batas pertanyaan per jam, panjang jawaban). Di bagian atas ada kartu 'Asisten KD': isi API KEY KHUSUS asisten (Base URL, Model, API key; contoh Groq https://api.groq.com/openai/v1 + openai/gpt-oss-20b) supaya kuota terpisah dari AI Provider Bot News; tombol Simpan, Tes Koneksi, Hapus Key (key tidak pernah ditampilkan ulang). Gunakan model chat (mis. openai/gpt-oss-20b), bukan model guard/whisper/tts; tombol 'Daftar Model' menampilkan model chat yang tersedia. Bila 'Tes Koneksi' gagal 403: key tidak punya izin atau modelnya bukan model chat. Key khusus dipakai sendiri dan tidak pernah jatuh ke provider Bot News; selama belum diisi, asisten sementara memakai AI Provider menu BOT. Kelompok angka lain: Auto Posting Prediksi (masa kunci sesi terkirim 6 jam, maks percobaan sesi gagal 3, kunci anti-tumpang-tindih 180 dtk, toleransi susulan), Keamanan Login (per akun dan per IP: batas salah & jendela waktu), Laporan Harian/Tarik Data (batas job dianggap gagal start/macet, pencegah job ganda), Jaringan & Cache (batas tunggu panggilan keluar, cache berita publik, cache ringkasan & filter Aktivitas), Bot News (tarikan sumber luar per putaran, maks artikel per klik manual), Asisten KD (panjang pertanyaan maks). Klik SIMPAN (tombol DEFAULT mengembalikan nilai bawaan di form sebelum disimpan). Daftar jadwal/shio/pasaran ada di tab Data Master. Nilai di luar rentang dijepit otomatis; berlaku ±15 detik. (2) 'Lap Admin · Operator Khusus': daftar operator (label + nama operator) yang dipisahkan dari Total Deposit di Lap Admin, mis. Blazz, Khanpay. Nama operator cocok bila mengandung teks itu (tidak peka huruf besar/kecil), maks 10. Hanya ADMIN yang bisa menyimpan.",
	},
	maintenance: {
		title: "Maintenance & Log",
		text: "Mode Maintenance: saat aktif operator tidak bisa login atau mengirim (admin tetap bisa); isi pesan lalu simpan. Retensi Activity Log: log lebih lama dari batas (default 7 hari, diatur di Pengaturan) dihapus otomatis tiap hari; 'Bersihkan sekarang' memangkas langsung.",
	},
};

/** Penjelasan umum, peran, dan pemecahan masalah. */
export const KB_GENERAL = `
PANEL: KD-Group Panel — panel operasional untuk operator website togel grup KD. Dibuat oleh KD.
LOGIN: Masuk dengan username & password dari admin. Salah password beberapa kali berturut-turut mengunci akun sementara (batas & lama diatur admin); minta admin 'buka kunci'. Sesi berlaku beberapa hari; bila 'Sesi tidak valid', login ulang. Tombol 'Keluar' di kanan atas.
ROLE: ADMIN (semua menu + menu Admin), OPERATOR (menu kerja harian sesuai akses yang diatur admin), VIEWER (hanya baca/terbatas), BOT (khusus modul Bot News, terkunci dari menu lain). Admin bisa membatasi menu per user. Bila sebuah menu tidak terlihat, artinya tidak diizinkan untuk akun itu — minta admin.
TAMPILAN: sidebar kiri berisi menu per grup (Utama, Laporan Harian, Live Chat, Admin); di HP memakai bilah bawah. Logo website akun tampil di kanan atas. Warna aksen mengikuti website akun.
MAINTENANCE: bila mode maintenance aktif, operator tidak bisa kirim/login; hanya admin.
UMUM PENYEBAB GAGAL: (1) cookie/PHPSESSID/token kedaluwarsa — ambil yang baru dari browser yang sedang login; (2) website belum punya token Telegram/LinkTree/Panel-Z di Admin > Website; (3) akun tidak punya akses website/menu; (4) kuota/layanan pihak ketiga (Telegram, GitHub Actions) sedang bermasalah — coba lagi nanti; (5) data duplikat diblokir sengaja agar tidak terkirim dua kali.
KEAMANAN: jangan membagikan password, cookie, token, atau API key kepada siapa pun termasuk asisten ini; asisten tidak butuh dan tidak boleh meminta data itu.
ASISTEN KD: widget chat melayang di kanan bawah, tersedia untuk SEMUA role (termasuk BOT). Tombol '−' menyembunyikan ke tepi kanan; tombol tab kecil di tepi memunculkannya lagi. Asisten hanya memberi panduan (tidak menjalankan aksi) dan memakai API key khusus yang diisi admin di Admin > Pengaturan Sistem (cadangan: AI Provider di Bot > Setting). SCREENSHOT: pengguna bisa menempelkan gambar langsung ke kolom chat dengan Ctrl+V (atau tombol klip kertas) agar asisten ikut melihat tampilan/galat yang dimaksud; gambar diperkecil di browser, dikirim ke penyedia AI hanya untuk pertanyaan itu, dan tidak disimpan. Hanya model yang mendukung gambar (mis. Gemini) yang bisa membacanya; bila modelnya tidak mendukung, asisten memberi tahu dan pertanyaan teks tetap bisa dikirim. Jangan kirim screenshot yang menampilkan password, saldo, atau data pribadi.
`.trim();

// ============================================================================
// KELUHAN UMUM (gejala -> penyebab -> langkah). `k` = frasa yang mungkin diketik user, dipisah '|' (huruf kecil).
// TAMBAHKAN entri baru setiap ada fitur/galat baru. Jawaban singkat, berurutan, tanpa rahasia.
// ============================================================================
export const KB_FAQ: { id: string; k: string; a: string }[] = [
	// --- Akun & login ---
	{ id: "lupa-password", k: "lupa password|lupa kata sandi|reset password|ganti password|password salah|tidak bisa login|gak bisa login|ga bisa masuk", a: "Panel tidak punya 'lupa password' mandiri. Minta ADMIN mengganti password di Admin › Users (edit user, isi password baru). Setelah diganti, sesi lama akun itu otomatis dicabut dan Anda login dengan password baru. Pastikan juga Caps Lock mati dan username benar." },
	{ id: "akun-terkunci", k: "akun terkunci|terkunci|dikunci|locked|terlalu banyak percobaan|salah password berkali", a: "Akun dikunci sementara setelah salah password beberapa kali berturut-turut (bawaan 5 kali, kunci 10 menit; admin bisa mengubahnya di Admin › Pengaturan Sistem). Tunggu sampai kunci habis, atau minta ADMIN membuka kunci (ikon kunci di Admin › Users). Pesan 'Terlalu banyak percobaan login gagal dari jaringan ini' berarti alamat jaringan (IP) dibatasi sementara — tunggu menit yang disebut di pesan." },
	{ id: "sesi-berakhir", k: "sesi tidak valid|sesi berakhir|keluar sendiri|logout sendiri|terlempar|login ulang terus|session expired panel", a: "Sesi login berlaku 21 hari (bawaan). Sesi juga dicabut otomatis bila ADMIN mengganti password/menonaktifkan/menghapus/me-rename akun Anda, atau bila jumlah sesi melebihi batas per user. Cukup login ulang. Kalau sering terlempar, kemungkinan akun dipakai di banyak perangkat sekaligus atau password baru saja diganti admin." },
	{ id: "maintenance", k: "maintenance|pemeliharaan|tidak bisa kirim|panel sedang|mode perbaikan", a: "Saat Mode Maintenance aktif, operator tidak bisa login atau mengirim; hanya ADMIN yang tetap bisa. Pesan pemeliharaan tampil di layar. ADMIN mematikannya di Admin › Maintenance & Log. Tunggu admin atau hubungi admin." },
	{ id: "menu-hilang", k: "menu tidak muncul|menu hilang|tidak ada menu|menu tidak terlihat|tidak bisa buka menu|menu tidak diizinkan|akses ditolak", a: "Menu yang tampil ditentukan role dan 'akses menu' per user di Admin › Users. Pesan 'Menu X tidak diizinkan untuk akun ini' berarti admin belum mencentang menu itu: minta admin membukanya. Menu Auto Prediksi dan Live Chat hanya untuk ADMIN/OPERATOR; menu Admin hanya ADMIN; akun BOT hanya melihat menu Bot News; VIEWER hanya baca." },
	{ id: "tampilan-lama", k: "tampilan lama|tidak berubah|belum update|fitur baru tidak muncul|cache|ctrl+f5|refresh keras", a: "Setelah ada pembaruan panel, tekan Ctrl+F5 (muat ulang tanpa cache). Di HP: tutup tab lalu buka lagi, atau hapus data situs di pengaturan browser. Pastikan koneksi internet aktif (ada banner merah bila offline)." },
	{ id: "panel-lemot", k: "lemot|lambat|berat|hang|macet|tidak responsif|loading lama|layar kosong|layar gelap|panas|kipas", a: "Langkah: (1) Ctrl+F5; (2) tutup tab panel yang dobel dan tab berat lain; (3) periksa koneksi (jaringan seluler yang lambat bisa membuat layar gelap sampai ±2 detik); (4) pindah menu lalu kembali; (5) bila hanya satu menu yang lambat, sebutkan menu & waktunya ke admin. Bila laptop terasa panas saat kotak Result berisi teks, itu sudah diperbaiki di versi terbaru — Ctrl+F5." },
	// --- Result & kirim ---
	{ id: "result-salah", k: "status salah|teks tidak terbaca|tidak terbaca|pasaran tidak dikenali|hasil tidak muncul|preview kosong|result kosong|tempel tidak jalan", a: "Tempel teks hasil pengeluaran dari Telegram UTUH tanpa diedit (harus memuat nama Pasaran dan Prize 1/2/3). Panel mengenali Pasaran, Prize, Shio, angka 2D lalu menampilkannya di 'Monitor hasil real-time'. Status harus 'BENAR' sebelum 'KIRIM SEMUA SISTEM'. Bila 'SALAH': ada bagian yang hilang/ketik ulang, atau nama pasaran belum dikenali — salin ulang dari sumber. Tombol 'Tempel' butuh izin clipboard browser; bila ditolak, tempel manual (Ctrl+V)." },
	{ id: "kirim-gagal", k: "kirim gagal|gagal kirim|telegram gagal|linktree gagal|panel-z gagal|panelz gagal|tidak terkirim|pengiriman gagal|diblokir", a: "Lihat hasil per website. TELEGRAM gagal → token/chat ID website belum diisi atau salah (Admin › Website). LINKTREE gagal → email/password LinkTree website salah/kosong. PANEL-Z gagal → URL/user/password Panel-Z salah/kosong. 'DIBLOKIR' → akun Anda belum diberi izin sistem itu di Admin › Users. 'Konfigurasi website tidak ditemukan' → data website belum dibuat admin. Setelah dibetulkan, kirim ulang HANYA sistem yang gagal (tombol kirim ulang); yang sudah berhasil tidak terkirim dobel." },
	{ id: "duplikat", k: "duplikat|sudah dikirim|sudah pernah dikirim|dobel|ganda|terkirim dua kali|kirim ulang", a: "Sistem mencegah kirim ganda: data yang sama ke website yang sama (oleh siapa pun) ditandai 'SUDAH DIKIRIM' dengan nama pengirim & waktu. Itu normal. Jika memang perlu mengirim ulang satu sistem (mis. Telegram gagal), gunakan kirim ulang per sistem. Peringatan '⚠ ... pencatatan anti-duplikat gagal' berarti pesan SUDAH terkirim — jangan kirim ulang, beri tahu admin." },
	{ id: "auto-prediksi-riwayat", k: "riwayat auto prediksi|history auto prediksi|riwayat job hilang|job hilang|riwayat tidak lengkap|history hilang|riwayat 7 hari", a: "Tabel riwayat di menu Auto Prediksi menampilkan SEMUA job selama 7 hari terakhir (bukan 30 baris terakhir); job tidak dihapus otomatis sebelum itu. Admin dapat mengubah lamanya 1-30 hari di Admin › Pengaturan Sistem › Auto Prediksi (Input Otomatis) › Riwayat job ditampilkan. Job lebih lama dari batas tidak tampil lagi. Job gagal tahap awal bisa dihapus dengan tombol COBA LAGI." },
	{ id: "tampilan-hp", k: "tampilan hp|di hp|layar hp|mobile|tombol tidak kelihatan|tombol terpotong|geser ke samping|tabel terpotong|tampilan kartu|responsive", a: "Di layar HP (lebar ≤ 640px) tabel yang punya tombol aksi tampil sebagai KARTU, bukan tabel lebar: jadwal Prediksi (Copy/Send Auto selebar kartu), Admin › Users (tombol Edit/Buka kunci/Hapus di bawah kartu), Sesi Aktif, riwayat Auto Prediksi, dan riwayat Tarik Data. Kartu Aktivitas tidak lagi menampilkan baris 'ISI / DATA' yang kosong. Tabel data murni (laporan Lap Admin/Motion/Mozart, PGA) tetap bisa digeser ke samping. Bila tampilan aneh setelah update, muat ulang dengan Ctrl+F5 (di HP: tutup lalu buka lagi tab)." },
	{ id: "toto-macau-auto", k: "toto macau otomatis|auto check toto macau|toto macao 5d|totomacau otomatis|posting otomatis panel-z|panel-z otomatis|angka toto macau|toto macau tidak naik|toto macau belum terkirim|auto posting tidak jalan toto|xxxx panel-z|cek dan isi sekarang|log kegiatan toto|sedang berjalan toto|toto macau tanpa klik", a: "Auto Check berjalan OTOMATIS tanpa klik: cron Cloudflare memicu GitHub Actions (toto-macau.yml) tiap 3 menit setelah jam draw atau saat ada baris menunggu, selain itu tiap 30 menit. Ia membaca nomor admin AG/AGWL mundur 7 hari lewat tombol [ >> ] (diatur di Pengaturan Sistem; Hitung: Yes; 4D jam 13,16,19,22,23,00, 5D jam 15 & 21) pakai PHPSESSID tersimpan akun berizin Panel-Z & menu Result, lalu mencocokkan dengan baris PASARAN + TANGGAL yang sama di Panel-Z: kosong/xxxx = diisi; sudah sama = SUDAH ADA; angka BERBEDA = dikoreksi ke angka admin (mode 2, angka lama tercatat di Keterangan 'DIKOREKSI'); baris belum dibuat Panel-Z (00:25) = MENUNGGU BARIS lalu diisi begitu muncul. Setiap hasil dibaca ulang untuk verifikasi. Kartu punya LOG KEGIATAN langsung (SEDANG BERJALAN / siaga). Tombol CEK & ISI SEKARANG hanya memaksa sekarang. Syarat: token GitHub di Admin › Integrasi (TES KONEKSI)." },
	{ id: "auto-prediksi-simpan-7-hari", k: "disimpan 7 hari|riwayat hilang|riwayat dihapus|data lama hilang|log lama|log toto macau hilang|riwayat auto prediksi dihapus|berapa lama riwayat|hapus otomatis|simpan berapa hari", a: "Riwayat job Auto Prediksi, catatan per draw Auto Check Toto Macau, dan LOG KEGIATAN hanya disimpan 7 hari ke belakang (batas 00:00 WIB hari ke-7); yang lebih lama tidak ditampilkan lagi dan dihapus otomatis sekali sehari (job yang masih berjalan tidak disentuh). Angka N diatur admin di Pengaturan Sistem › Auto Prediksi › 'Riwayat Auto Prediksi disimpan' (1–30 hari). Bila perlu bukti angka lama, lihat Aktivitas atau admin website; catatan Auto Prediksi tidak bisa dipulihkan setelah dihapus. Bila rentang periksa Toto Macau dibuat lebih panjang dari N, baris lama yang tampak hanya sebatas N hari." },
	{ id: "toto-macau-user-lain", k: "user lain otomatis|dobel cek|double check|kirim ganda|operator lain otomatis|semua user otomatis|user lain juga|user lain toto macau|siapa yang diproses|website tanpa sesi|toto macau tidak jalan untuk user|syarat auto check", a: "Auto Check berjalan per WEBSITE dan otomatis untuk SEMUA website yang punya minimal satu akun memenuhi syarat: (1) Auto Prediksi akun itu AKTIF, (2) status AKTIF, peran ADMIN/OPERATOR, (3) izin Panel-Z + menu Result & Auto Prediksi, (4) PHPSESSID admin website tersimpan di tab 'Sesi Website', (5) Panel-Z website terisi. Satu website diproses SEKALI untuk semua user (kunci per website, sesi akun pertama yang hidup dipakai): tidak ada pengecekan atau posting ganda dan semua user melihat hasil yang sama. Tombol 'Cek & isi sekarang' tepat setelah pemeriksaan (<1 menit) tidak memeriksa ulang. Website tanpa akun memenuhi syarat dilewati. Bila satu-satunya sesi habis, log menulis 'sesi habis' — tempel PHPSESSID baru." },
	{ id: "toto-macau-mengirim-tersangkut", k: "mengirim tidak selesai|status mengirim terus|mengirim tersangkut|sedang mengirim lama|baris ganda|dilewati panel-z|panel-z hanya menyimpan|pemicu otomatis tidak berjalan|pemicu cron|kartu tidak update|log tidak bergerak|tanggal belum diposting", a: "Status MENGIRIM yang lama = putaran Auto Check terhenti di tengah jalan (biasanya kena batas panggilan Cloudflare saat backlog besar); baris itu otomatis dikerjakan ulang >10 menit kemudian dan sekarang backlog dikerjakan TERBARU dulu dalam beberapa siklus ±3 menit. 'Baris ganda' = Panel-Z punya dua baris pasaran+tanggal sama (mis. hasil Tambah Manual Result): semuanya disamakan dengan angka admin. DILEWATI 'Panel-Z hanya menyimpan sampai …' = tanggal itu sudah dihapus Panel-Z (menyimpan ±7 hari), tidak bisa diisi. Di kartu ada 'Pemicu cron terakhir …'; merah ⚠ bila >45 menit = pemicu otomatis mati: cek token GitHub di Admin › Integrasi (TES KONEKSI) lalu tekan CEK & ISI SEKARANG. Kartu memperbarui diri tiap 5–30 detik." },
	{ id: "toto-macau-7-hari", k: "7 hari|tujuh hari|angka sebelumnya|tanggal sebelumnya|tombol >>|halaman admin berikutnya|periksa mundur|lookback|batas koreksi massal|terlalu banyak angka berbeda|koreksi ditahan|pemetaan keliru", a: "Auto Check memeriksa angka admin mundur sampai 7 hari dari hari ini (Pengaturan Sistem › Auto Check Toto Macau › 'Periksa angka admin sampai', 1–14 hari): halaman admin dibaca lewat tombol [ >> ] (20 baris per halaman: ?start=20&end=40…) sampai tanggal batas terlewati, lalu tiap angka dicocokkan dengan baris Panel-Z pasaran + tanggal yang sama. Pengaman: bila angka Panel-Z yang BERBEDA dalam satu putaran lebih dari 'Batas koreksi massal' (bawaan 10), itu tanda pemetaan tanggal/pasaran keliru, bukan salah ketik — koreksi otomatis DITAHAN, baris ditandai BEDA ANGKA, ada popup & log merah. Periksa pemetaan dulu; naikkan batas hanya bila memang banyak angka salah. Putaran pertama setelah rentang dibesarkan bisa memakai beberapa siklus (±3 menit tiap siklus) sampai semua baris beres." },
	{ id: "toto-macau-koreksi", k: "angka panel-z salah|angka berbeda dikoreksi|koreksi angka|beda angka panel-z|angka toto macau salah|ditimpa otomatis|sys_totomacau_correct|koreksi angka berbeda", a: "Angka admin AG/AGWL dianggap benar. Di mode 2 (bawaan koreksi = 1) baris Panel-Z yang sudah berisi angka BERBEDA — hasil input manual atau auto yang salah — otomatis diperbaiki ke angka admin, lalu dibaca ulang untuk memastikan. Angka lama tercatat di kolom Keterangan ('DIKOREKSI: Panel-Z berisi …') dan di LOG KEGIATAN. Yang diubah hanya baris dengan pasaran + tanggal yang cocok persis dengan baris admin berstatus Hitung: Yes; baris tanggal lain tidak disentuh. Mau menahan koreksi? Admin › Pengaturan Sistem › Auto Check Toto Macau › 'Koreksi angka berbeda' = 0: angka berbeda hanya ditandai BEDA ANGKA + popup peringatan. Mode 1 tidak pernah mengirim atau mengoreksi." },
	{ id: "toto-macau-baris-tidak-ada", k: "too many subrequests|subrequests by single worker|menunggu baris|baris belum dibuat|baris tidak ada|baris totomacau tidak ada|toto macau baris tidak ada|panel-z tidak ada barisnya|tanggal yang terbaca", a: "Galat 'Too many subrequests' = satu putaran Auto Check memakai terlalu banyak panggilan jaringan (batas Cloudflare 50); sudah diperbaiki (log ditulis sekaligus, proses lewat GitHub Actions). Bila muncul lagi, tekan CEK & ISI SEKARANG sekali lagi: sisa baris dilanjutkan. MENUNGGU BARIS (dulu 'BARIS TIDAK ADA') = Panel-Z belum punya baris pasaran + tanggal itu (baris dibuat tiap hari 00:25); akan diisi otomatis begitu muncul. Keterangan menyebut tanggal yang TERBACA untuk pasaran tersebut. Panel-Z membagi daftar Result per halaman (100 baris, ?hal=result&no=N, terbaru dulu); Auto Check membaca halaman berikutnya sampai batas hari terlewati (maks 12 halaman), jadi baris di halaman 2+ ikut terbaca. Baris tidak pernah dibuat otomatis oleh panel: bila Panel-Z memang tidak membuatnya, tambahkan manual." },
	{ id: "auto-prediksi-urutkan", k: "urutkan auto prediksi|sort auto prediksi|menu urutkan|sortir|urut terbaru|urut terlama|perlu dicek dulu|cari yang gagal dulu|gagal paling atas|susun tabel", a: "Di menu Auto Prediksi ada pilihan URUTKAN di atas tabel Riwayat (di sebelah kolom cari) dan di kartu Auto Check Toto Macau: Terbaru dulu, Terlama dulu, Perlu dicek dulu (GAGAL / BEDA ANGKA / BELUM TERISI naik ke atas), Website A–Z, Pasaran A–Z, Status A–Z. Satu pilihan berlaku untuk kedua tabel dan diingat di browser ini. Kombinasikan dengan kolom cari (mis. ketik HUGO lalu urut 'Perlu dicek dulu') untuk memeriksa cepat." },
	{ id: "auto-prediksi-gagal-otomatis", k: "popup peringatan gagal|peringatan auto prediksi|popup merah|auto prediksi gagal|gagal dicoba ulang|coba ulang otomatis|retry otomatis|hitung gagal|tidak terhitung|lupa cek admin|cari job|kolom cari auto prediksi|search auto prediksi|percobaan ulang", a: "Job Auto Prediksi yang GAGAL dicoba ulang otomatis oleh server (tiap menit) sebanyak 2 kali dengan jeda 2 menit: gagal 00:23 → coba 00:25 → coba 00:27 (terakhir). Tidak perlu kirim manual. Bila angka sudah masuk tetapi Hitung gagal, yang diulang hanya Hitung (angka tidak dikirim dobel). Kolom Keterangan menampilkan 'Percobaan ulang n/2'. Bila tetap GAGAL setelah itu, muncul popup merah PERINGATAN di menu mana pun (sekali, tombol BUKA AUTO PREDIKSI); cek manual di admin website (penyebab umum: PHPSESSID habis, pasaran tidak ditemukan). Pakai kolom pencarian di atas tabel riwayat untuk mencari website/pasaran/status GAGAL. Admin dapat mengubah jumlah & jeda di Pengaturan Sistem › Auto Prediksi (Input Otomatis); fitur harus tetap AKTIF." },
	{ id: "auto-prediksi", k: "auto prediksi|nomor keluar|phpsessid habis|uji gagal|input otomatis gagal|hitung gagal|sesi habis admin website", a: "Auto Prediksi butuh PHPSESSID admin website yang MASIH HIDUP: ambil dari Chrome yang sedang login admin website (F12 › Application › Cookies), tempel di kartu website, klik Simpan, lalu 'Uji (tanpa kirim)'. Bila sesi habis input gagal dan Anda input manual; tempel PHPSESSID baru. Pastikan tombol 'Aktifkan' di atas berstatus AKTIF. Pesan 'sudah sampai tahap mengubah data di admin' berarti cek MANUAL di admin website dan jangan diulang otomatis." },
	// --- Prediksi ---
	{ id: "prediksi-tidak-terkirim", k: "prediksi tidak terkirim|auto posting tidak jalan|prediksi otomatis|send auto gagal|prediksi belum terkirim|penutup tidak terkirim", a: "Auto Posting hanya mengirim bila: (1) Auto Posting AKTIF (Admin › Auto Posting); (2) ada operator yang sedang login; (3) website operator punya token & chat ID Telegram PREDIKSI; (4) waktunya jatuh tempo (sesi 02:35, 06:15, 08:40, 12:40, 16:00, 21:20, 23:25; penutup 06:15 & 16:00; toleransi susulan bawaan 25 menit). Tombol 'Send Auto' di menu Prediksi mengirim ke website yang belum terkirim hari ini; kolom Status menunjukkan 'x dari y website'." },
	// --- Invest ---
	{ id: "invest-expired", k: "session expired|invest gagal|scan 0 data|scan kosong|scan berhenti|hasil invest kosong|cek koneksi session|phpsessid invest|koderedis", a: "Di AutoCheck Invest: login ulang ke panel agen, ambil PHPSESSID baru (dan koderedis bila tetap 'session expired'), isi di 'Setting panel agen', Simpan, lalu 'Cek koneksi/session' sampai OK. Scan menghasilkan 0 data → isi 'Daftar pasaran' manual. Scan terhenti → 'Lanjutkan scan'; mulai ulang → 'Reset' lalu 'Mulai scan'. Hasil ada di 'User lewat batas' (klik 'Refresh hasil')." },
	// --- Laporan harian ---
	{ id: "ubah-jadwal-prediksi", k: "ubah jadwal prediksi|ganti jam prediksi|tambah sesi prediksi|jam auto posting|ubah jam sesi|tambah pasaran prediksi|hapus pasaran prediksi|jadwal prediksi diatur|jam penutup", a: "ADMIN: Admin › Data Master › 'Jadwal Prediksi' (jam, nama sesi, pasaran tiap sesi; tambah sesi di BAWAH) dan 'Kata-kata Penutup Prediksi' (jam & kalimat). SIMPAN, berlaku ±15 detik. Jangan menukar urutan sesi di tengah hari: nomor sesi (PRED-n) dipakai penjaga anti-kirim-ganda. Salah isi? KEMBALIKAN KE BAWAAN. Angka masa kunci/percobaan ada di Pengaturan Sistem › Auto Posting Prediksi." },
	{ id: "ubah-shio", k: "ubah shio|peta shio|shio salah|shio tidak sesuai|zodiak|shio angka 00|koreksi shio|status salah shio|nama shio", a: "ADMIN: Admin › Data Master › 'Peta Shio'. 12 nama untuk sisa bagi 12 dua angka terakhir Prize 1 (sisa 1 = nama pertama … sisa 0 = nama ke-12), plus shio khusus angka 00. Nama huruf saja, tidak boleh kembar. Dipakai server untuk memeriksa baris 'Shio :' (BENAR/SALAH) dan oleh pratinjau di browser. Bila hasil terlihat salah shio, cek peta ini dulu; KEMBALIKAN KE BAWAAN memulihkan peta asli." },
	{ id: "tambah-pasaran", k: "tambah pasaran|pasaran baru|pasaran tidak dikenal|slug panelz|panelz gagal pasaran|pasaran tidak terkirim panelz|ubah pasaran|hapus pasaran|peta pasaran|daftar pasaran invest|kode pasaran", a: "ADMIN: Admin › Data Master. 'Peta Pasaran → Panel-Z': baris 'NAMA PASARAN = slug' (mis. HK SIANG = hk-siang); pasaran yang tidak ada di peta TIDAK terkirim ke Panel-Z, dan slug yang salah membuat kiriman pasaran itu gagal. 'Daftar Pasaran AutoCheck Invest': baris 'kode = NAMA' (kode dari panel agen, mis. p6680); tiap user bisa menimpa daftarnya sendiri di menu AutoCheck Invest. Pasaran baru di jadwal prediksi ditambah lewat 'Jadwal Prediksi'." },
	{ id: "token-github", k: "token github|gh token|ganti token github|token kedaluwarsa|token github salah|tes koneksi github|github tidak tersambung|resource not accessible|bot news turbo gagal|invest turbo gagal|isi token", a: "ADMIN: Admin › Integrasi › kelompok GitHub Actions. Buat Fine-grained token di GitHub (Actions: Read and write; centang repo KD-scraper DAN KD-Group-Panel), tempel di 'Token GitHub', SIMPAN, lalu klik TES KONEKSI — tiap jalur (Tarik Data, Bot News turbo, Invest turbo) diperiksa dan diberi diagnosa. 403 'Resource not accessible' = izin/daftar repo di token kurang; 404 = nama repo salah atau token tidak mencakup repo itu; 401 = token salah/kedaluwarsa. Token tidak ditampilkan ulang (hanya 4 karakter terakhir) dan tidak dicatat di log. Tidak perlu lagi mengubah variabel di Cloudflare." },
	{ id: "ubah-linktree-url", k: "ubah linktree|url linktree|api key linktree|linktree gagal|ganti alamat linktree|session login gagal linktree|alamat web berita|ganti domain berita|domain admin|struk disbursement url|alamat panel|public url", a: "ADMIN: Admin › Integrasi. LinkTree: URL login, URL kirim notifikasi, dan API key (rahasia; kunci lama masih tertanam di kode repo — sebaiknya isi kunci baru di sini). Alamat web berita sendiri dipakai untuk backlink/caption Facebook/sitemap. Domain admin (mis. suksesbogil.com) adalah pagar Auto Input: akses hanya ke domain itu dan sub-domainnya. Kolom kosong atau tombol BAWAAN = kembali ke nilai awal." },
	{ id: "dashboard-angka", k: "angka dashboard tidak update|grafik per jam kosong|donat sukses|rasio sukses|berikutnya jam|jadwal prediksi dashboard|operator teraktif|dashboard lambat update|batang merah", a: "Angka & grafik Dashboard dihitung dari log aktivitas HARI INI (WIB) dan di-cache singkat (bawaan 25 detik; admin bisa mengubahnya di Pengaturan Sistem › Jaringan & Cache), jadi bisa tertinggal beberapa detik — muat ulang halaman bila perlu. Grafik kosong = belum ada aktivitas pada jam itu; batang merah = aktivitas berstatus GAGAL/ERROR; donat 'sukses' = Berhasil/(Berhasil+Gagal). Jadwal & hitung mundur 'Berikutnya' mengikuti Admin › Data Master › Jadwal Prediksi. Operator hanya melihat data akunnya sendiri; 'Operator teraktif' hanya untuk ADMIN." },
	{ id: "bot-angka-situs", k: "total hari ini situs sendiri|situs sendiri hari ini|angka situs sendiri|blogger ada situs tidak ada|hitungan situs sendiri|kartu blogger situs facebook|tren 7 hari bot|kenapa angka bot beda|batas harian situs|total tayang", a: "Dashboard Bot punya tiga kartu jalur dengan susunan sama (Blogger, Situs Sendiri, Template Facebook): masing-masing menampilkan angka HARI INI, total semua, status, dan batas/keterangan. Situs Sendiri tidak punya batas harian (hanya maks per putaran di Setting), jadi batangnya penuh redup dan tertulis 'Tanpa batas harian'. 'Total tayang' di kartu kesehatan = Blogger + Situs Sendiri. Hari dihitung WIB (tengah malam reset). Tren 7 hari memakai tanggal tayang tiap jalur. Bila angka tampak tidak cocok: klik tombol refresh di 'Jalankan sekarang'; Template FB hanya menghitung yang sudah di-generate (bukan yang error)." },
	{ id: "lap-total-deposit-salah", k: "total deposit salah|total deposit minus|total deposit negatif|total withdraw salah|total deposit tidak sesuai|total deposit beda|total qris blazz|total khanpay|angka total tidak cocok", a: "Ada dua kartu deposit: 'Deposit Semua Operator' = jumlah deposit SEMUA operator tanpa dikurangi apa pun (contoh 156.100.650), dan 'Total Deposit' = jumlah itu DIKURANGI operator khusus (Blazz/Khanpay, diatur di Admin > Pengaturan Sistem). Contoh: 156.100.650 − Blazz 155.121.800 = 978.850. Total Withdraw = total kolom Withdraw (bukan Reject). Bila angkanya aneh (minus / Withdraw kecil): angka dihitung dari baris per operator, jadi seharusnya sama dengan jumlah kolom di halaman History Operator; bila tidak, klik TARIK DATA lagi. Bila masih salah: cek nama operator khusus di Pengaturan Sistem (cocok bila mengandung teks itu) dan bandingkan dengan halaman History Operator di admin website." },
	{ id: "lap-tarik-lama", k: "tarik data lama|tarik data gagal|progres macet|cookie kedaluwarsa|tarik data tidak jalan|scraper|github actions|menunggu github|lap admin kosong", a: "Tarik data Lap Admin dijalankan scraper di GitHub Actions (±1–3 menit; bila banyak user, antre per sumber admin). Syarat: Link Admin + Cookie Admin di Laporan Harian › Setting masih berlaku. 'Cookie Admin kedaluwarsa/ditolak' → ambil Cookie baru (PHPSESSID=...) dari browser yang login, simpan, tarik ulang. Job yang mati/menggantung otomatis ditutup GAGAL; klik TARIK DATA lagi. Anda boleh pindah menu selama menunggu — progres tampil di 'Progres & riwayat tarik data'." },
	{ id: "lap-total", k: "total deposit tidak sesuai|total deposit salah|total blazz|total khanpay|operator khusus|total withdraw|history operator", a: "Total Deposit = total tabel History Operator DIKURANGI operator khusus; 'Total <operator>' (mis. Blazz/Khanpay) dan Total Withdraw ikut tanggal yang ditarik. Operator khusus diatur ADMIN di Admin › Pengaturan Sistem (tulis persis seperti nama di History Operator). Bila angka tidak cocok: pastikan rentang tanggal benar, tarik ulang, dan cek nama operator khusus tidak salah ketik." },
	{ id: "lap-motion-pga", k: "skrip tidak jalan|terkirim ke panel|motion tidak masuk|pga pending kosong|data pga tidak update|update terakhir|token motion|lap motion kosong", a: "Lap Motion/PGA Pending/Mozart diambil lewat Console BROWSER (bukan server): buka tab Motion/Mozart yang sudah login, F12 › Console (ketik 'allow pasting' sekali), tempel skrip dari panduan 'Cara pakai', Enter, tunggu 'terkirim ke panel OK', lalu 'Muat Ulang' di panel. PGA Pending: biarkan tab Motion TETAP TERBUKA; label 'Update terakhir N detik lalu' berwarna merah (>15 dtk) berarti skrip berhenti — jalankan lagi. Token/cookie yang kedaluwarsa membuat data kosong: login ulang di Motion dan jalankan skrip lagi." },
	// --- Live chat ---
	{ id: "livechat-bot-tidak-muncul", k: "tombol bot tidak muncul|robot tidak muncul|tidak ada tombol|livechat bot tidak muncul|console livechat|allow pasting|bookmark tidak jalan|pasang bot", a: "Pasang bot lewat Console (bookmark tidak jalan di halaman DayLiveChat): buka halaman DayLiveChat CS & login → F12 › Console → ketik 'allow pasting' + Enter (sekali) → di panel klik 'SALIN KODE CONSOLE' (Live Chat › Sesi Chat) → tempel di Console + Enter. Tombol 🤖 muncul di pojok kanan bawah halaman DayLiveChat. Bila muncul popup 'Bot gagal dimuat', situs memblokir skrip — beri tahu admin. Setelah halaman di-refresh, tempel kode lagi (Kunci Bot tidak perlu diisi ulang)." },
	{ id: "livechat-sesi-kosong", k: "sesi chat tidak muncul|daftar sesi kosong|sinkron|belum ada sesi|sesi tidak terdeteksi|kunci bot tidak valid|kunci userscript", a: "Sesi muncul di Live Chat › Sesi Chat hanya bila bot (🤖) aktif di tab DayLiveChat dan Kunci Bot benar. Ambil Kunci Bot dari kartu 'KUNCI BOT KAMU' (tombol Tampilkan/Salin) dan tempel di tombol 🤖, simpan, nyalakan. 'Kunci userscript tidak valid' → kunci salah/lama; salin lagi dari kartu (bila pernah menekan 'Buat kunci baru', kunci lama mati). Kunci Bot bersifat PER PENGGUNA: sesi akun lain tidak akan tampil di menu Anda. Tab DayLiveChat harus tetap terbuka." },
	{ id: "livechat-bot-spam", k: "bot spam|bot membalas berkali|balasan dobel|balas terus|bot balas banyak|bot kirim berulang|satu balasan saja|bot ikut spam", a: "Bot hanya membalas SATU kali per rentetan pesan member: sesudah membalas, bot diam walau member terus spam, selama jeda antar pesan member tidak lebih dari 90 detik. Bila member diam >90 detik lalu menulis lagi, bot membalas 1x lagi. Kalau bot masih membalas berkali-kali, kemungkinan bot lama masih berjalan di tab/PC lain atau skrip lama belum diganti: tutup bot lama, muat ulang halaman DayLiveChat, lalu tempel kode Console terbaru dari Live Chat › Sesi Chat (SALIN KODE CONSOLE)." },
	{ id: "livechat-tidak-membalas", k: "bot tidak membalas|tidak membalas otomatis|auto reply tidak jalan|balasan tidak terkirim|bot aktif tapi diam|template kosong", a: "Bot membalas hanya bila SEMUA ini terpenuhi: (1) tombol 🤖 di halaman DayLiveChat berstatus AKTIF (tombol Nyalakan) dan tab masih terbuka; (2) switch 'BOT AKTIF' sesi itu dinyalakan di panel; (3) ada template balasan AKTIF milik Anda (Live Chat › Template Balasan — tiap pengguna punya template sendiri; tanpa template bot diam); (4) member menulis: pesan pertama dibalas setelah ±30 detik bila belum dibalas CS, pesan ≥2 berturut-turut dibalas langsung, tetapi HANYA SATU kali per rentetan: selama member masih menulis tanpa jeda lebih dari 90 detik bot tidak membalas lagi (tidak ikut spam); setelah member diam >90 detik lalu menulis lagi, itu dianggap rentetan baru dan dibalas 1x lagi. Sesi yang member-nya sudah keluar dimatikan otomatis." },
	{ id: "livechat-ganda", k: "balasan ganda|bot membalas dua kali|bot dobel|balas berulang", a: "Pastikan hanya SATU cara bot yang jalan untuk akun yang sama (Console/Tampermonkey/Agent Node.js) dan hanya satu tab DayLiveChat yang menjalankannya. Tempel kode Console dua kali di tab yang sama tidak menggandakan bot (panel kecil hanya terbuka/tertutup), tetapi dua tab/dua cara berbeda akan membalas ganda." },
	{ id: "gemini-model-404", k: "gemini 404|model tidak tersedia|no longer available|no longer available to new users|gemini tidak bisa|gemini gagal|gemini bot gagal|tes koneksi gagal 404|model dicabut|model not found", a: "Key Gemini Anda TIDAK salah. Galat 'HTTP 404 ... model ... is no longer available to new users' artinya Google sudah mencabut model itu (mis. gemini-2.5-flash) untuk akun baru. Solusi: Bot › Setting › AI Provider, klik DAFTAR MODEL, pilih model yang tampil (varian flash / flash-lite terbaru, atau yang disarankan Google di pesan galat), SIMPAN, lalu TES lagi. Alias 'gemini-flash-latest' (bawaan panel) biasanya selalu mengikuti model terbaru. Nama model Google berganti dari waktu ke waktu, jadi jangan menghafal nama -- selalu ambil dari DAFTAR MODEL. Hal yang sama berlaku untuk provider lain (Groq dsb) bila model dihentikan." },
	{ id: "tes-facebook", k: "tes facebook|facebook gagal|posting facebook gagal|fanspage tidak terposting|token facebook|page access token|page id salah|fb gagal terus|auto share facebook gagal|izin pages_manage_posts|token kedaluwarsa facebook", a: "Klik TES FACEBOOK di Bot › Setting › Sosial & Promo (Page ID & token boleh diisi dulu tanpa menyimpan). Hasilnya menyebut penyebab pasti: 'BUKAN halaman' = Anda memakai token USER (ambil token halaman di Graph API Explorer, pilih Halaman); 'KEDALUWARSA/TIDAK VALID/dicabut' = buat token baru; 'IZIN KURANG' = butuh pages_manage_posts + pages_read_engagement dan pembuat token harus ADMIN halaman; 'Page ID SALAH' = cek angkanya; 'BATAS KECEPATAN/MEMBLOKIR' = tunggu. Tulisan kecil di pojok kartu hanya berarti token TERSIMPAN, bukan valid. Penyebab 'kedaluwarsa' tersering: token pendek (~1-2 jam) dari Graph API Explorer; perpanjang token user di Access Token Debugger (Extend), lalu ambil token halaman dari /me/accounts. Artikel yang gagal karena token rusak ditandai error dan tidak diulang." },
	{ id: "make-foto-hashtag", k: "foto tidak muncul|postingan make tanpa foto|make tanpa gambar|hashtag make|caption make|pratinjau kosong|berita lapakstore88 tanpa gambar|make facebook polos|caption seperti template fb", a: "Posting Make berbentuk tautan hanya menampilkan judul umum situs ('Berita — LapakStore88') tanpa foto, karena situs berita memuat isi lewat JavaScript sehingga Facebook tidak menemukan gambar per artikel. Solusi: di Make pakai modul Facebook Pages › 'Create a Post with Photos' (bukan 'Create a Post'), Image input type = URL, isi URL dengan Enclosures[].url dari modul RSS; Caption = field Description dari RSS. Umpan RSS panel sudah memuat caption lengkap di Description (judul, ringkasan, tautan artikel, promosi, hashtag kategori + hashtag tetap dari Admin › Data Master) tanpa AI. Artikel tanpa gambar akan gagal di modul foto: pasang filter agar dilewati." },
	{ id: "rss-tampil-dashboard", k: "rss tampil dashboard|news-feed.xml dashboard|umpan rss kosong|rss tidak muncul|feed xml tidak jalan|rss make tidak terbaca|rss error make|bukan xml", a: "Alamat umpan yang benar: <alamat panel>/public/news-feed.xml. Bila yang tampil malah Dashboard panel (bukan teks XML), berarti versi panel belum ter-deploy atau rute belum terdaftar -- tekan Ctrl+F5, tunggu deploy selesai, lalu coba lagi. Yang benar: halaman menampilkan XML berisi <item> berjudul artikel (di Chrome kadang tampil sebagai teks/pohon XML). Make/IFTTT menolak umpan yang isinya HTML. Umpan hanya memuat artikel yang SUDAH tayang di web berita sendiri (maks 30 terbaru); kosong bila belum ada artikel tayang." },
	{ id: "fb-rss-fanspage", k: "rss facebook|auto post fanspage|autopost fanspage|posting fanspage gagal|token facebook gagal|facebook gagal terus|cara lain facebook|dlvr|ifttt|publer|make.com|zapier facebook|umpan rss|news-feed", a: "Cara tanpa app/token Meta sendiri: panel menyediakan umpan RSS artikel situs Anda di <alamat panel>/public/news-feed.xml (30 artikel terbaru yang tayang di web berita). Tempel alamat itu di layanan RSS-ke-Facebook (dlvr.it, IFTTT, Publer, Make, Zapier) lalu sambungkan Fanspage lewat login Facebook di layanan itu; mereka memakai app Meta mereka sendiri. Cara lama (Page ID + Page Access Token di Bot › Setting › Sosial & Promo) tetap ada; bila gagal terus, penyebab tersering: token milik user bukan token HALAMAN, token kedaluwarsa, izin pages_manage_posts kurang, atau Page ID bukan milik token itu. Gagal posting ke Facebook tidak menghentikan bot, hanya dicatat. Layanan RSS mengecek umpan tiap beberapa menit-1 jam dan paket gratis membatasi jumlah posting." },
	{ id: "modelark-provider", k: "modelark|model ark|byteplus|doubao|seed model|volcengine|ark api|base url modelark|tambah modelark", a: "ModelArk (BytePlus/ByteDance, model Seed/Doubao) kompatibel dengan format OpenAI, jadi bisa dipasang di Bot › Setting › AI Provider › Tambah Provider: klik tombol cepat ModelArk (mengisi Nama dan Base URL https://ark.ap-southeast.bytepluses.com/api/v3), tempel API key Anda, lalu isi Model dengan ID model dari konsol ModelArk Anda (ID tiap akun/region bisa berbeda; kadang berbentuk endpoint 'ep-...'), SIMPAN, lalu TES. Key terikat region: key dari region Asia-Pasifik tidak jalan di host region lain (mis. eu-west) -- samakan Base URL dengan region key Anda. Akun China (Volcengine) memakai host berbeda, ubah Base URL sesuai konsol Anda. Galat 401/403 = key atau region salah; 404 = ID model salah." },
	{ id: "popup-panjang-tutup", k: "popup tidak bisa ditutup|popup kepanjangan|tombol tutup hilang|tidak bisa menutup|popup menutupi layar|cara menutup popup|tutup popup", a: "Tekan tombol Esc di keyboard untuk menutup popup apa pun. Pada popup berisi teks panjang (mis. hasil tes banyak model) isi teksnya bisa digulir di dalam kotak dan tombol TUTUP selalu terlihat di bawahnya." },
	{ id: "gemini-429-kuota", k: "429|kuota terlampaui|exceeded your current quota|model pro gemini gagal|gemini pro 429|rate limit gemini|live-preview|bidirectional|bidigeneratecontent", a: "HTTP 429 'You exceeded your current quota' di Gemini artinya key gratis Anda tidak punya jatah untuk model itu (umumnya semua model 'pro' dan sebagian 'preview'); key-nya sendiri benar. Model '*-live-preview' hanya untuk streaming WebSocket dan TIDAK bisa dipakai untuk menulis artikel. Isi daftar model provider hanya dengan model flash / flash-lite yang lolos tes (✅), buang yang ❌ agar tidak membuang waktu dan jeda; model yang gagal otomatis diistirahatkan sementara dan bot memakai cadangan berikutnya." },
	// --- Asisten ---
	{ id: "asisten-sibuk", k: "asisten sibuk|asisten tidak menjawab|asisten error|api key bermasalah|asisten belum aktif|jawaban lama", a: "Asisten KD memakai API key khusus yang diisi ADMIN di Admin › Pengaturan Sistem › Asisten KD. 'Asisten sedang sibuk atau API key bermasalah' → minta admin klik TES KONEKSI (membedakan key salah vs model lambat/diblokir) dan memilih model yang cepat (bukan alias '*-latest'). 'Batas pertanyaan per jam tercapai' → tunggu jam berikutnya. 'Asisten KD sedang dimatikan admin' → admin menyalakannya di Pengaturan Sistem. Lampiran screenshot (Ctrl+V/klip) hanya terbaca bila model mendukung gambar (mis. Gemini)." },
	// --- Admin ---
	{ id: "admin-tambah-user", k: "tambah user|buat akun|akun baru|user baru|tambah operator|buat user|daftar akun", a: "ADMIN: Admin › Users › TAMBAH USER. Isi username, nama, password (wajib untuk akun baru), role (ADMIN/OPERATOR/VIEWER/BOT), status AKTIF, website yang boleh dipakai (kode dipisah koma, mis. HUGO,FOLA), centang akses menu, serta izin Telegram/LinkTree/Panel-Z. Pengguna baru juga perlu menambah template balasan sendiri bila memakai Live Chat." },
	{ id: "admin-website-baru", k: "website baru|tambah website|token telegram|chat id|kode website|logo website|data website", a: "ADMIN: Admin › Website › isi data per website: nama tampilan, token & chat ID Telegram (result) dan Telegram prediksi, email & password LinkTree, URL/user/password Panel-Z. Website harus punya kode yang dikenali sistem agar logo & tema tampil. Mengganti kode website memindahkan datanya secara atomik. Operator hanya bisa memakai website yang tercantum di akunnya (Admin › Users)." },
	{ id: "admin-cron", k: "cron|jalankan sekarang|auto posting mati|url cron|jadwal otomatis", a: "Auto Posting digerakkan cron: Cloudflare (tiap 5 menit) dan/atau layanan cron eksternal yang memanggil 'URL CRON' tiap menit (Admin › Auto Posting). Tombol 'Jalankan Sekarang' memaksa satu putaran. Tick tanpa slot jatuh tempo kini langsung selesai tanpa beban. Pastikan statusnya AKTIF dan ada operator login." },
	// --- Bot News ---
	{ id: "bot-blogger", k: "blogger belum terhubung|hubungkan ulang blogger|oauth|client id|izin google|putus tiap 7 hari|kode izin google", a: "Bot News › Setting › Blogger: klik hubungkan, izinkan akun Google, lalu tempel URL LENGKAP dari address bar setelah klik Izinkan ('Kode izin Google tidak ditemukan' = URL tidak lengkap). Isi Blog ID. Agar tidak putus tiap 7 hari: Google Cloud Console › Google Auth Platform › Audience, ubah Publishing status dari Testing ke In production, lalu hubungkan ulang sekali. Jenis client: Desktop app." },
	{ id: "bot-tidak-posting", k: "artikel tidak diposting|bot berita tidak jalan|ai provider tidak aktif|artikel terlalu pendek|ai balas|auto post berita", a: "Periksa peringatan merah di Bot News › Dashboard: 'Blogger belum terhubung' → Hubungkan Ulang; 'tidak ada AI provider aktif' → Kelola/aktifkan provider di Setting › AI Provider (key, model, kuota/masa aktif belum habis). Galat 'AI balas artikel terlalu pendek' = model terlalu lemah/salah — pilih model lain. Pastikan toggle AUTO-POST menyala dan ada sumber berita aktif di menu Sumber Berita." },
];

// ============================================================================
// ARTI PESAN GALAT yang muncul di layar (cocok sebagian teks, huruf kecil).
// ============================================================================
export const KB_ERRORS: { m: string; a: string }[] = [
	{ m: "galat tampilan (", a: "Data dari server sudah diterima tetapi layar gagal menggambarnya (bug tampilan, bukan data Anda yang hilang). Muat ulang halaman (Ctrl+F5); bila berulang, catat nama menu di dalam kurung dan laporkan ke admin." },
	{ m: "sesi tidak valid atau telah berakhir", a: "Sesi login habis/dicabut. Login ulang. Jika terjadi berulang, tanyakan admin apakah akun diubah/dikunci." },
	{ m: "akun terkunci sementara", a: "Terlalu banyak salah password. Tunggu beberapa menit atau minta admin membuka kunci di Admin › Users." },
	{ m: "terlalu banyak percobaan login gagal dari jaringan ini", a: "IP jaringan dibatasi sementara karena banyak percobaan gagal. Tunggu sesuai menit di pesan." },
	{ m: "tidak diizinkan untuk akun ini", a: "Menu itu belum dibuka admin untuk akun Anda. Minta admin mencentangnya di Admin › Users." },
	{ m: "hanya untuk admin atau operator", a: "Menu itu tidak tersedia untuk role Anda (VIEWER/BOT). Hubungi admin bila perlu akses." },
	{ m: "akun bot hanya bisa mengakses fitur bot", a: "Role BOT hanya boleh memakai modul Bot News. Gunakan akun OPERATOR/ADMIN untuk menu lain." },
	{ m: "akses ditolak. hanya admin", a: "Fitur itu khusus ADMIN." },
	{ m: "admin terakhir tidak boleh dihapus", a: "Harus selalu ada minimal satu ADMIN; buat/ubah akun ADMIN lain dulu." },
	{ m: "username sudah digunakan", a: "Pilih username lain (tidak boleh sama dengan akun yang ada, huruf besar/kecil dianggap sama)." },
	{ m: "password wajib untuk akun baru", a: "Saat menambah user baru kolom password harus diisi." },
	{ m: "konfigurasi website", a: "Data website itu (token/URL) belum dibuat. ADMIN mengisinya di Admin › Website." },
	{ m: "kamu tidak punya akses ke website", a: "Kode website itu tidak ada di daftar website akun Anda. Minta admin menambahkannya di Admin › Users." },
	{ m: "sudah dikirim", a: "Data yang sama sudah pernah dikirim ke website itu (pencegah ganda) — normal; lihat nama pengirim & waktu di pesan." },
	{ m: "pengecekan anti-duplikat", a: "Database pencatat anti-duplikat sedang tidak terbaca, jadi pengiriman SENGAJA ditahan agar tidak ganda. Coba lagi sebentar; bila tetap, hubungi admin (Turso)." },
	{ m: "pencatatan anti-duplikat gagal", a: "Pesan SUDAH terkirim tetapi pencatatannya gagal. JANGAN kirim ulang; beri tahu admin." },
	{ m: "phpsessid kosong", a: "Isi & simpan PHPSESSID di menu AutoCheck Invest (Setting panel agen) dulu." },
	{ m: "session expired", a: "Sesi panel agen/admin website habis. Login ulang di sumbernya, ambil PHPSESSID/cookie baru, simpan di panel." },
	{ m: "cookie admin kedaluwarsa", a: "Cookie Admin di Laporan Harian › Setting sudah tidak berlaku. Ambil yang baru dari browser yang login lalu tarik data lagi." },
	{ m: "gagal memicu github actions", a: "Panel gagal menjalankan scraper di GitHub. Lihat angka di kurung: 401 = token GH_TOKEN salah/kedaluwarsa; 403 'Resource not accessible by personal access token' = token tidak punya izin (Actions: Read and write) atau repo KD-scraper tidak dicentang di token; 404 = nama repo (GH_REPO) atau workflow scrape.yml tidak ditemukan; 500/502/503 = gangguan di sisi GitHub, tunggu beberapa menit lalu tarik data lagi. Perbaikan token hanya bisa dilakukan admin server (buat Fine-grained token di GitHub, pasang sebagai secret GH_TOKEN di Cloudflare panel-worker > Settings > Variables and Secrets). Jangan kirim token ke siapa pun." },
	{ m: "belum dikonfigurasi (secret gh_token", a: "GitHub Actions belum disambungkan di server. Hanya admin server yang bisa memperbaiki (secret GH_TOKEN)." },
	{ m: "turso belum dikonfigurasi", a: "Database Turso belum disambungkan di server (TURSO_URL/TURSO_TOKEN). Hubungi admin server." },
	{ m: "live chat bot belum dikonfigurasi", a: "Secret LIVECHAT_BOT_KEY belum diatur di server. Hubungi admin server." },
	{ m: "kunci userscript tidak valid", a: "Kunci Bot salah/lama. Salin ulang dari kartu 'KUNCI BOT KAMU' di Live Chat › Sesi Chat, tempel di tombol 🤖." },
	{ m: "job ini sudah sampai tahap mengubah data", a: "Proses sudah mengubah data di admin website. Periksa MANUAL di admin website; jangan diulang otomatis agar tidak dobel." },
	{ m: "job dihentikan sebelum selesai", a: "Proses scraper berhenti sebelum selesai (runner gagal/dibatalkan/waktu habis). Klik TARIK DATA lagi." },
	{ m: "melebihi batas waktu", a: "Sumber data terlalu lambat. Coba lagi nanti atau persempit rentang tanggal." },
	{ m: "blog id belum diisi", a: "Isi Blog ID di Bot News › Setting › Blogger lalu simpan." },
	{ m: "client id / client secret oauth belum diisi", a: "Isi Client ID & Client Secret (Desktop app) di Bot News › Setting › Blogger › Client OAuth, simpan, lalu hubungkan." },
	{ m: "kode izin google tidak ditemukan", a: "Tempel URL LENGKAP dari address bar setelah klik Izinkan di Google." },
	{ m: "ai balas artikel terlalu pendek", a: "Model AI tidak mengikuti instruksi/terlalu lemah. Ganti model di Bot News › Setting › AI Provider." },
	{ m: "http 403 forbidden", a: "Penyedia AI menolak: key salah/tidak punya izin, atau permintaan diblokir. Admin: Pengaturan Sistem › Asisten KD › TES KONEKSI memberi diagnosa; pastikan model chat yang diizinkan akun." },
	{ m: "batas pertanyaan per jam tercapai", a: "Kuota pertanyaan Asisten KD per jam habis; coba lagi jam berikutnya atau minta admin menaikkan batasnya." },
	{ m: "asisten sedang sibuk atau api key bermasalah", a: "Admin perlu TES KONEKSI di Pengaturan Sistem › Asisten KD; kemungkinan model lambat atau key bermasalah." },
	{ m: "base url diganti ke alamat lain", a: "Demi keamanan key lama tidak dipakai untuk alamat baru; isi API key BARU saat mengganti Base URL." },
	{ m: "terlalu besar", a: "Berkas/screenshot melebihi batas. Potong bagian yang perlu saja lalu coba lagi." },
	{ m: "tidak bisa membaca gambar", a: "Model asisten tidak mendukung gambar. Kirim pertanyaan tanpa screenshot, atau admin memakai model yang mendukung gambar (mis. Gemini)." },
];

// ============================================================================
// GLOSARIUM KOLOM / ISTILAH (label di layar -> arti). Dipakai pula test gerbang CI: setiap label UI harus tercakup.
// ============================================================================
export const KB_GLOSSARY: Record<string, string> = {
	"Cantumkan sumber + backlink di tiap artikel": "Bot News › Setting › Konten & Artikel: bila dinyalakan tiap artikel mencantumkan sumber + tautan balik (juga keterangan 'Foto: sumber'). Di bawahnya 'Kotak Promo di Artikel': isi link promo; KOSONG = kotak promo tidak dipasang.",
	"Tanggal Sampai": "Menu Aktivitas (filter): batas akhir rentang tanggal; dipasangkan dengan 'Tanggal Dari'. Klik TERAPKAN untuk memfilter, RESET untuk mengosongkan.",
	"Role": "Admin › Users: ADMIN (semua menu + Admin), OPERATOR (kerja harian sesuai akses), VIEWER (hanya baca), BOT (khusus Bot News).",
	"Status Akun": "Admin › Users: AKTIF (boleh login), NONAKTIF (tidak boleh login, sesi dicabut), TERKUNCI (kena batas salah password; buka lewat ikon kunci).",
	"Catatan Admin": "Admin › Users: catatan bebas admin tentang akun (mis. nama pemilik). Tidak tampil ke pengguna.",
	"URL feed": "Bot News › Sumber Berita: alamat RSS/Atom feed berawalan http/https; dipilih Jenis (RSS atau Google News) dan Kategori (mis. Umum, Nasional). Nama & URL wajib.",
	"API key": "Bot News › Setting › AI Provider (dan kartu Asisten KD): kunci penyedia AI. Disimpan di server dan tidak pernah ditampilkan utuh lagi (hanya 4 karakter terakhir). Isi kunci baru bila mengganti Base URL.",
	"Paragraf minimal": "Bot News › Setting › Konten & Artikel: jumlah paragraf terkecil per artikel (bawaan 12–18 paragraf, ±800–1.500 kata).",
	"Paragraf maksimal": "Bot News › Setting › Konten & Artikel: jumlah paragraf terbesar per artikel; bersama 'Paragraf minimal' menentukan panjang tulisan.",
	"Gambar per artikel": "Bot News › Setting: jumlah gambar tiap artikel (bawaan 4: 1 gambar utama + foto dari isi artikel sumber, disebar di antara paragraf).",
	"Gaya penulisan ulang (prompt)": "Bot News › Setting: instruksi gaya yang dikirim ke AI saat menulis ulang berita. Ubah hanya bila ingin gaya berbeda.",
	"Label/Tag postingan (pisah koma)": "Bot News › Setting: label Blogger untuk tiap postingan, dipisah koma.",
	"Interval auto-post (menit)": "Bot News › Setting › Jadwal Posting: jeda antar posting otomatis. Dipadukan dengan 'Jatah Blogger', 'Artikel per proses', dan 'Batas artikel / hari' untuk membatasi laju posting.",
	"Client OAuth": "Bot News › Setting › Blogger: isi Client ID & Client Secret hanya bila mengganti client di Google Cloud (jenis Desktop app); disimpan lewat SIMPAN SETTING. Agar koneksi tidak putus tiap 7 hari ubah Publishing status ke In production lalu hubungkan ulang.",
	"Client ID": "Bot News › Setting › Blogger › Client OAuth: ID client Google Cloud (Desktop app).",
	"Client Secret": "Bot News › Setting › Blogger › Client OAuth: rahasia client Google Cloud; tidak ditampilkan ulang.",
	"Auto-share tiap post ke Facebook Page": "Bot News › Setting › Sosial & Promo: bila dinyalakan tiap artikel yang terposting dibagikan ke Facebook Page (butuh Page ID dan Page Access Token).",
	"Ganti Page Access Token": "Bot News › Setting › Sosial & Promo: tempel token halaman Facebook baru bila yang lama kedaluwarsa; token tidak ditampilkan ulang.",
	"TES FACEBOOK": "Bot News › Setting › Sosial & Promo: memeriksa Page ID + Page Access Token (yang diketik, atau yang tersimpan bila kosong) dan menyebut penyebab pastinya bila gagal. Membuat 1 posting tersembunyi lalu langsung menghapusnya; token tidak pernah ditampilkan.",
	"Link Fanspage Facebook": "Bot News › Setting › Sosial & Promo: tautan Fanspage yang dipromosikan otomatis di tiap artikel.",
	"Link Saluran WhatsApp": "Bot News › Setting › Sosial & Promo: tautan Saluran WhatsApp yang dipromosikan otomatis di tiap artikel.",
	"Tampilkan banner": "Bot News › Setting › Banner Promosi (Berita Terkini): menampilkan banner di sidebar situs Berita Terkini; isi Gambar banner (URL), Link tujuan banner, dan Teks banner.",
	"Gambar banner": "Banner Promosi: alamat (URL) gambar banner untuk sidebar Berita Terkini.",
	"Link tujuan banner": "Banner Promosi: tautan yang dibuka saat banner diklik.",
	"Teks banner": "Banner Promosi: teks pada banner.",
	"Memproses Pengiriman": "Popup tunggu saat 'KIRIM SEMUA SISTEM' berjalan (memvalidasi data, menghubungkan sistem, mengirim). Jangan tutup tab sampai hasil per website muncul.",
	"COPY GAMBAR": "Bot News › Template FB: menyalin gambar artikel terpilih ('buka gambar asli' membukanya di tab baru); bila artikel tidak punya gambar tombolnya tidak aktif.",
	"COPY CAPTION": "Bot News › Template FB: menyalin caption hasil generate AI untuk dipakai di Facebook. Riwayat yang sudah di-generate dicatat supaya tidak dobel.",
	"SESI CHAT TERDETEKSI": "Live Chat › Sesi Chat: daftar sesi dari Kotak Masuk DayLiveChat yang disinkronkan bot 🤖 (milik Anda saja). Nyalakan switch 'BOT AKTIF' per sesi.",
};

export function buildKnowledgeText(): string {
	const pages = Object.entries(KB_PAGES).map(([k, v]) => `## MENU ${v.title} (id: ${k})\n${v.text}`);
	const tabs = Object.entries(KB_ADMIN_TABS).map(([k, v]) => `## ADMIN › ${v.title} (tab: ${k})\n${v.text}`);
	const faq = KB_FAQ.map((f) => `## KELUHAN (${f.id})\n${f.a}`);
	const errs = KB_ERRORS.map((e) => `## GALAT "${e.m}"\n${e.a}`);
	const gloss = Object.entries(KB_GLOSSARY).map(([l, a]) => `## ISTILAH ${l}\n${a}`);
	return [KB_GENERAL, ...pages, ...tabs, ...faq, ...errs, ...gloss].join("\n\n");
}

// ---------------------------------------------------------------------------
// Pemilihan bagian yang relevan (hemat token: provider gratis seperti Groq
// punya batas token/menit kecil, jadi tidak seluruh manual dikirim tiap tanya).
// Selalu dikirim: info umum + indeks 1 baris tiap menu/tab. Ditambah teks
// lengkap 3 bagian paling cocok dengan pertanyaan (+ riwayat singkat).
// ---------------------------------------------------------------------------
const STOP = new Set("yang dan di ke dari untuk dengan atau ini itu apa bagaimana gimana cara bisa tidak kok mau saya aku kita dong nih ya sih kalau agar supaya pada akan sudah belum lagi juga tapi karena adalah dalam oleh the".split(" "));
// kata awam -> id bagian (menambah skor)
// [pola, id bagian, bobot (bawaan 3)]. Pola yang sangat spesifik diberi bobot lebih tinggi supaya tidak kalah oleh kata umum (mis. 'bot').
const SYNONYMS: [RegExp, string[], number?][] = [
	[/kirim|send|telegram|linktree|panel-?z|duplikat|tempel|paste/, ["result", "prediction"]],
	[/prediksi|penutup|jadwal|sesi jam/, ["prediction", "autopost", "auto-input"]],
	[/token github|gh_token|integrasi|linktree|tes koneksi|domain admin|struk|repo github|resource not accessible|isi token/, ["integrasi"], 9],
	[/shio|zodiak|data master|peta pasaran|slug|ubah jadwal|ganti jam|tambah sesi|tambah pasaran|pool tebak|kata penutup/, ["datamaster", "autopost"], 8],
	[/cookie|phpsessid|session|expired|kedaluwarsa|token/, ["lap-setting", "auto-input", "invest", "lap-admin"]],
	[/tarik|scrape|register|selisih|operator|blazz|khanpay|deposit|withdraw|total/, ["lap-admin", "lapops"]],
	[/motion|pga/, ["lap-motion", "pga-pending"]],
	[/mozart/, ["lap-mozart"]],
	[/user|akun|password|role|akses|kunci|terkunci|hapus|tambah/, ["users"]],
	[/website|situs|token telegram|chat id/, ["sites"]],
	[/log|riwayat|aktivitas|filter/, ["activity", "maintenance"]],
	[/maintenance|retensi/, ["maintenance"]],
	[/pengaturan|setting|batas|limit|durasi|sesi login/, ["lapops", "lap-setting", "invest"]],
	[/bot|berita|blogger|artikel|rss|sumber|facebook|fb|ai provider|api key|groq/, ["bot-dashboard", "bot-sources", "bot-config", "bot-history", "bot-fbdirect"]],
	[/live ?chat|auto-?reply|userscript|tampermonkey|console|f12|kunci ?bot|bot ?key|bookmark|snippet|daylivechat|cs chat/, ["livechat-sessions", "livechat-templates"], 9],
	[/balas|template/, ["livechat-sessions", "livechat-templates"]],
	[/dashboard|beranda|ringkasan/, ["home"]],
	[/invest|line|pasaran/, ["invest"]],
];

function firstSentence(t: string, max = 120): string {
	const s = t.split(/(?<=[.!?])\s/)[0] || t;
	return s.length > max ? s.slice(0, max - 1) + "…" : s;
}

export function selectKnowledge(question: string, history: string[] = [], top = 3): string {
	const q = (question + " " + history.slice(-2).join(" ")).toLowerCase();
	const words = [...new Set(q.split(/[^a-z0-9\-]+/).filter((w) => w.length >= 3 && !STOP.has(w)))];
	const entries: { id: string; tab: boolean; title: string; text: string }[] = [
		...Object.entries(KB_PAGES).map(([id, v]) => ({ id, tab: false, title: v.title, text: v.text })),
		...Object.entries(KB_ADMIN_TABS).map(([id, v]) => ({ id, tab: true, title: v.title, text: v.text })),
	];
	const boost = new Map<string, number>();
	for (const [re, ids, w] of SYNONYMS) if (re.test(q)) for (const id of ids) boost.set(id, (boost.get(id) ?? 0) + (w ?? 3));
	const scored = entries
		.map((e) => {
			const hay = (e.title + " " + e.text).toLowerCase();
			const titleLc = e.title.toLowerCase();
			let sc = boost.get(e.id) ?? 0;
			for (const w of words) {
				if (titleLc.includes(w)) sc += 3;
				else if (hay.includes(w)) sc += 1;
			}
			return { e, sc };
		})
		.filter((x) => x.sc > 0)
		.sort((a, b) => b.sc - a.sc)
		.slice(0, top);
	const index = entries.map((e) => `- ${e.tab ? "Admin › " : ""}${e.title}: ${firstSentence(e.text)}`).join("\n");
	const detail = scored.map(({ e }) => `## ${e.tab ? "ADMIN › " : "MENU "}${e.title}\n${e.text}`).join("\n\n");

	// Keluhan umum yang mirip (frasa cocok = +4, kata cocok = +1). Maks 3, minimal skor 4.
	const faq = KB_FAQ.map((f) => {
		let sc = 0;
		for (const ph of f.k.split("|")) {
			if (!ph) continue;
			// cocok bila frasa persis ada, ATAU semua kata bermaknanya ada (urutan bebas): 'bot livechat tidak membalas' ~ 'bot tidak membalas'.
			const ws = ph.split(/[^a-z0-9\-]+/).filter((w) => w.length >= 3);
			if (q.includes(ph) || (ws.length >= 2 && ws.every((w) => q.includes(w)))) sc += 4;
		}
		const kw = new Set(f.k.split(/[^a-z0-9\-]+/).filter((w) => w.length >= 4));
		for (const w of words) if (kw.has(w)) sc += 1;
		return { f, sc };
	})
		.filter((x) => x.sc >= 4)
		.sort((a, b) => b.sc - a.sc)
		.slice(0, 3);
	// Pesan galat yang dikutip pengguna (cocok sebagian teks).
	const errs = KB_ERRORS.filter((x) => q.includes(x.m)).slice(0, 3);
	// Istilah/kolom yang disebut (label lengkap, atau seluruh kata bermakna label ada di pertanyaan).
	const gloss = Object.entries(KB_GLOSSARY)
		.filter(([label]) => {
			const l = label.toLowerCase();
			if (q.includes(l)) return true;
			const ws = l.split(/[^a-z0-9]+/).filter((w) => w.length >= 4);
			return ws.length >= 2 && ws.every((w) => q.includes(w));
		})
		.slice(0, 3);
	const extra = [
		faq.length ? "KELUHAN UMUM YANG MIRIP (pakai sebagai dasar jawaban):\n" + faq.map((x) => `- ${x.f.a}`).join("\n") : "",
		errs.length ? "ARTI PESAN GALAT YANG DISEBUT:\n" + errs.map((x) => `- "${x.m}": ${x.a}`).join("\n") : "",
		gloss.length ? "ISTILAH/KOLOM YANG DISEBUT:\n" + gloss.map(([l, a]) => `- ${l}: ${a}`).join("\n") : "",
	]
		.filter(Boolean)
		.join("\n\n");
	return `${KB_GENERAL}\n\nINDEKS MENU:\n${index}\n\nPENJELASAN LENGKAP BAGIAN YANG RELEVAN:\n${detail || "(tidak ada yang cocok — tanyakan balik menu mana yang dimaksud)"}${extra ? "\n\n" + extra : ""}`;
}
